services:
  grpc-demo:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - USER_ID=$USER_ID
    volumes:
      - ..:/workspace
    stdin_open: true
    tty: true
